import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import {
  DynamicContextProvider,
  DynamicWagmiConnector,
  EthereumWalletConnectors,
} from '../lib/dynamic';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DynamicContextProvider
        settings={{
          environmentId: '2ddebf12-13c3-49c8-ba67-c2ecb3da5edc',
          walletConnectors: [EthereumWalletConnectors],
          // eventsCallbacks: {
          //   onAuthSuccess: (args) => {
          //     console.log('onAuthSuccess was called', args);
          //   },
          // },
        }}
      >
        <DynamicWagmiConnector>
          <body className={inter.className}>{children}</body>
        </DynamicWagmiConnector>
      </DynamicContextProvider>
    </html>
  );
}
